services:
  db:
    image: postgres:15
    container_name: postgres-petshop
    environment:
      POSTGRES_DB: petshop_db
      POSTGRES_USER: gilberto
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"