services:
  db:
    image: postgres:15
    container_name: postgres-petshop
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - "/Volumes/storange mac/tcc-petshop-backend/postgres_data:/var/lib/postgresql/data"